
-- ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
-- NCPL 2026 SEED DATA
-- ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ

-- 0. Clear existing data
TRUNCATE scores, matches, players, teams, tournaments, users RESTART IDENTITY CASCADE;

-- 1. Create Admin User
INSERT INTO users (name, email, password_hash, role) 
VALUES ('System Admin', 'admin@smartleague.com', '$2a$10$Xm7M1mY...dummy_hash', 'admin');

-- 2. Create Tournament
INSERT INTO tournaments (name, year, status) 
VALUES ('National Cricket Premier League 2026', 2026, 'upcoming');

-- 3. Create Users, Teams, and Players
INSERT INTO users (id, name, email, password_hash, role) VALUES (2, 'Akash Rahane', 'akash.rahane.2@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (3, 'Ishant Meredith', 'ishant.meredith.3@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (4, 'Aryan Nair', 'aryan.nair.4@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (5, 'Riley Arora', 'riley.arora.5@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (6, 'Vijay Warrier', 'vijay.warrier.6@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (7, 'Prasidh Markande', 'prasidh.markande.7@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (8, 'Shivam Sams', 'shivam.sams.8@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (9, 'Karun Nair', 'karun.nair.9@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (10, 'Ravi Singh', 'ravi.singh.10@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (11, 'Sandeep Arora', 'sandeep.arora.11@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (12, 'Prasidh Dhawan', 'prasidh.dhawan.12@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (13, 'Anil Gowtham', 'anil.gowtham.13@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (14, 'Riley Nagarkoti', 'riley.nagarkoti.14@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (15, 'Sandeep Rahul', 'sandeep.rahul.15@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (16, 'Karun Sakariya', 'karun.sakariya.16@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (17, 'Arshdeep Meredith', 'arshdeep.meredith.17@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (18, 'Kamlesh Sharma', 'kamlesh.sharma.18@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (19, 'Harshal Ashwin', 'harshal.ashwin.19@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (20, 'Mayank Ahmed', 'mayank.ahmed.20@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (21, 'Akash Warrier', 'akash.warrier.21@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (22, 'Varun Chahar', 'varun.chahar.22@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (23, 'Rajvardhan Singh', 'rajvardhan.singh.23@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (24, 'Anil Reddy', 'anil.reddy.24@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (25, 'Prithvi Meredith', 'prithvi.meredith.25@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (26, 'Ruturaj Brar', 'ruturaj.brar.26@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (27, 'Hardik Singh', 'hardik.singh.27@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (28, 'Vaibhav Arora', 'vaibhav.arora.28@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (29, 'Axar Samson', 'axar.samson.29@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (30, 'Ruturaj Mills', 'ruturaj.mills.30@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (31, 'Harshal Pandey', 'harshal.pandey.31@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (32, 'Nikhil Kumar', 'nikhil.kumar.32@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (33, 'Umesh Mehta', 'umesh.mehta.33@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (34, 'Rohit Ahmed', 'rohit.ahmed.34@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (35, 'Basil Jadhav', 'basil.jadhav.35@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (36, 'Vaibhav Uthappa', 'vaibhav.uthappa.36@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (37, 'Avesh Gaikwad', 'avesh.gaikwad.37@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (38, 'Arshdeep Jadhav', 'arshdeep.jadhav.38@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (39, 'Sandeep Rayudu', 'sandeep.rayudu.39@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (40, 'Krishnappa Singh', 'krishnappa.singh.40@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (41, 'Shardul Negi', 'shardul.negi.41@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (42, 'Anoop Gowtham', 'anoop.gowtham.42@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (43, 'Pawan Ashwin', 'pawan.ashwin.43@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (44, 'Krunal Markande', 'krunal.markande.44@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (45, 'Hardik Sharma', 'hardik.sharma.45@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (46, 'Arjun Rahul', 'arjun.rahul.46@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (47, 'Krunal Singh', 'krunal.singh.47@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (48, 'Lokesh Singh', 'lokesh.singh.48@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (49, 'Rohit Sharma', 'rohit.sharma.49@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (50, 'Ambati Thampi', 'ambati.thampi.50@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (51, 'Tim Thakur', 'tim.thakur.51@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (52, 'Sandeep Stubbs', 'sandeep.stubbs.52@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (53, 'Dinesh Negi', 'dinesh.negi.53@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (54, 'Mayank Thampi', 'mayank.thampi.54@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (55, 'Mohit Stubbs', 'mohit.stubbs.55@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (56, 'Mukesh Juyal', 'mukesh.juyal.56@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (57, 'Varun Krishna', 'varun.krishna.57@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (58, 'Rahul Verma', 'rahul.verma.58@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (59, 'Deepak Rayudu', 'deepak.rayudu.59@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (60, 'Mukesh David', 'mukesh.david.60@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (61, 'Saurabh Tewatia', 'saurabh.tewatia.61@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (62, 'Basil Patel', 'basil.patel.62@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (63, 'T Natarajan Rahul', 't natarajan.rahul.63@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (64, 'Karthik Dhawan', 'karthik.dhawan.64@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (65, 'Krishnappa Ahmed', 'krishnappa.ahmed.65@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (66, 'Varun Singh', 'varun.singh.66@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (67, 'Krunal Jadhav', 'krunal.jadhav.67@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (68, 'Ruturaj Mehta', 'ruturaj.mehta.68@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (69, 'Tushar Mills', 'tushar.mills.69@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (70, 'Shardul Sharma', 'shardul.sharma.70@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (71, 'Harshal Hangargekar', 'harshal.hangargekar.71@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (72, 'Navdeep Singh', 'navdeep.singh.72@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (73, 'Tristan Karthik', 'tristan.karthik.73@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (74, 'Sandeep Ashwin', 'sandeep.ashwin.74@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (75, 'Deepak Sharma', 'deepak.sharma.75@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (76, 'Ajinkya Gowtham', 'ajinkya.gowtham.76@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (77, 'Deepak Deshpande', 'deepak.deshpande.77@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (78, 'Sandeep Sharma', 'sandeep.sharma.78@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (79, 'Suresh Iyer', 'suresh.iyer.79@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'captain');
INSERT INTO users (id, name, email, password_hash, role) VALUES (80, 'Pawan Yadav', 'pawan.yadav.80@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (81, 'Pawan Shami', 'pawan.shami.81@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (82, 'Kedar Bumrah', 'kedar.bumrah.82@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (83, 'Vaibhav Juyal', 'vaibhav.juyal.83@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (84, 'Dinesh Singh', 'dinesh.singh.84@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (85, 'Daniel Jadhav', 'daniel.jadhav.85@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (86, 'Ravi Varma', 'ravi.varma.86@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (87, 'Axar Singh', 'axar.singh.87@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (88, 'Shreyas Iyer', 'shreyas.iyer.88@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO users (id, name, email, password_hash, role) VALUES (89, 'Nikhil Agarwal', 'nikhil.agarwal.89@league.com', '$2a$10$Xm7M1mY...dummy_hash', 'player');
INSERT INTO teams (id, name, captain_id) VALUES (1, 'Hyderabad Hawks', 2);
INSERT INTO teams (id, name, captain_id) VALUES (2, 'Bangalore Blasters', 13);
INSERT INTO teams (id, name, captain_id) VALUES (3, 'Chennai Chargers', 24);
INSERT INTO teams (id, name, captain_id) VALUES (4, 'Mumbai Mavericks', 35);
INSERT INTO teams (id, name, captain_id) VALUES (5, 'Delhi Dominators', 46);
INSERT INTO teams (id, name, captain_id) VALUES (6, 'Kolkata Knights', 57);
INSERT INTO teams (id, name, captain_id) VALUES (7, 'Punjab Panthers', 68);
INSERT INTO teams (id, name, captain_id) VALUES (8, 'Rajasthan Royals XI', 79);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (2, 1, 'batsman', 419, 0, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (3, 1, 'wicket-keeper', 446, 7, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (4, 1, 'wicket-keeper', 454, 10, 8);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (5, 1, 'batsman', 10, 11, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (6, 1, 'wicket-keeper', 280, 11, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (7, 1, 'bowler', 355, 7, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (8, 1, 'all-rounder', 168, 4, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (9, 1, 'wicket-keeper', 286, 12, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (10, 1, 'wicket-keeper', 473, 17, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (11, 1, 'batsman', 423, 1, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (12, 1, 'batsman', 33, 17, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (13, 2, 'batsman', 55, 14, 11);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (14, 2, 'wicket-keeper', 25, 11, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (15, 2, 'batsman', 211, 8, 11);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (16, 2, 'batsman', 429, 1, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (17, 2, 'bowler', 81, 11, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (18, 2, 'bowler', 231, 2, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (19, 2, 'bowler', 114, 17, 8);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (20, 2, 'bowler', 388, 14, 10);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (21, 2, 'all-rounder', 165, 11, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (22, 2, 'all-rounder', 271, 1, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (23, 2, 'all-rounder', 32, 6, 10);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (24, 3, 'batsman', 175, 13, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (25, 3, 'batsman', 196, 10, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (26, 3, 'bowler', 341, 17, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (27, 3, 'bowler', 28, 6, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (28, 3, 'all-rounder', 288, 14, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (29, 3, 'all-rounder', 420, 7, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (30, 3, 'all-rounder', 99, 5, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (31, 3, 'batsman', 407, 2, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (32, 3, 'all-rounder', 135, 15, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (33, 3, 'batsman', 287, 17, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (34, 3, 'wicket-keeper', 458, 17, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (35, 4, 'batsman', 118, 4, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (36, 4, 'bowler', 336, 19, 11);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (37, 4, 'all-rounder', 244, 8, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (38, 4, 'bowler', 248, 13, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (39, 4, 'all-rounder', 41, 11, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (40, 4, 'wicket-keeper', 406, 7, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (41, 4, 'batsman', 94, 0, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (42, 4, 'wicket-keeper', 335, 4, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (43, 4, 'bowler', 47, 6, 10);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (44, 4, 'batsman', 37, 17, 8);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (45, 4, 'wicket-keeper', 180, 13, 11);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (46, 5, 'batsman', 438, 16, 10);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (47, 5, 'wicket-keeper', 287, 17, 8);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (48, 5, 'all-rounder', 459, 14, 10);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (49, 5, 'bowler', 357, 9, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (50, 5, 'wicket-keeper', 424, 7, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (51, 5, 'wicket-keeper', 97, 1, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (52, 5, 'all-rounder', 267, 8, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (53, 5, 'all-rounder', 263, 15, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (54, 5, 'batsman', 344, 12, 11);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (55, 5, 'batsman', 175, 19, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (56, 5, 'batsman', 446, 13, 8);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (57, 6, 'batsman', 322, 1, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (58, 6, 'all-rounder', 25, 1, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (59, 6, 'all-rounder', 431, 5, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (60, 6, 'wicket-keeper', 280, 4, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (61, 6, 'batsman', 288, 14, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (62, 6, 'all-rounder', 32, 1, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (63, 6, 'wicket-keeper', 474, 8, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (64, 6, 'all-rounder', 356, 8, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (65, 6, 'bowler', 36, 17, 7);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (66, 6, 'bowler', 310, 17, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (67, 6, 'batsman', 251, 13, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (68, 7, 'batsman', 113, 12, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (69, 7, 'all-rounder', 405, 5, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (70, 7, 'batsman', 367, 13, 8);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (71, 7, 'wicket-keeper', 208, 6, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (72, 7, 'all-rounder', 134, 4, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (73, 7, 'all-rounder', 450, 15, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (74, 7, 'wicket-keeper', 175, 19, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (75, 7, 'all-rounder', 77, 7, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (76, 7, 'bowler', 434, 10, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (77, 7, 'all-rounder', 216, 15, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (78, 7, 'all-rounder', 434, 12, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (79, 8, 'batsman', 98, 3, 5);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (80, 8, 'wicket-keeper', 250, 18, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (81, 8, 'wicket-keeper', 223, 16, 10);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (82, 8, 'bowler', 346, 5, 12);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (83, 8, 'wicket-keeper', 491, 8, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (84, 8, 'all-rounder', 11, 19, 13);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (85, 8, 'bowler', 80, 0, 9);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (86, 8, 'batsman', 298, 11, 11);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (87, 8, 'bowler', 379, 6, 6);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (88, 8, 'batsman', 43, 7, 14);
INSERT INTO players (user_id, team_id, role, runs, wickets, matches_played) VALUES (89, 8, 'batsman', 90, 2, 11);

-- 4. Matches (Round Robin Schedule)
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (1, 1, 1, 2, '2026-06-01T15:00:00.000Z', 'Eden Gardens', 'completed', 2);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (1, 1, 181, 8, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (1, 2, 186, 9, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (2, 1, 1, 3, '2026-06-02T15:00:00.000Z', 'Eden Gardens', 'completed', 1);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (2, 1, 181, 7, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (2, 3, 177, 9, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (3, 1, 1, 4, '2026-06-03T15:00:00.000Z', 'Arun Jaitley Stadium', 'completed', 1);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (3, 1, 193, 7, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (3, 4, 174, 1, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (4, 1, 1, 5, '2026-06-04T15:00:00.000Z', 'Eden Gardens', 'completed', 1);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (4, 1, 184, 5, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (4, 5, 164, 2, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (5, 1, 1, 6, '2026-06-05T15:00:00.000Z', 'M. Chinnaswamy Stadium', 'completed', 1);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (5, 1, 151, 9, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (5, 6, 148, 7, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (6, 1, 1, 7, '2026-06-06T15:00:00.000Z', 'Eden Gardens', 'completed', 1);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (6, 1, 165, 8, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (6, 7, 158, 4, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (7, 1, 1, 8, '2026-06-07T15:00:00.000Z', 'Hyderabad International Stadium', 'completed', 1);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (7, 1, 154, 5, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (7, 8, 151, 4, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (8, 1, 2, 3, '2026-06-08T15:00:00.000Z', 'Arun Jaitley Stadium', 'completed', 3);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (8, 2, 159, 6, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (8, 3, 160, 9, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (9, 1, 2, 4, '2026-06-09T15:00:00.000Z', 'M. Chinnaswamy Stadium', 'completed', 4);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (9, 2, 155, 4, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (9, 4, 157, 5, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (10, 1, 2, 5, '2026-06-10T15:00:00.000Z', 'Hyderabad International Stadium', 'completed', 5);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (10, 2, 150, 8, 20.0);
INSERT INTO scores (match_id, team_id, runs, wickets, overs) VALUES (10, 5, 152, 3, 20.0);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (11, 1, 2, 6, '2026-06-11T15:00:00.000Z', 'Eden Gardens', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (12, 1, 2, 7, '2026-06-12T15:00:00.000Z', 'M. Chinnaswamy Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (13, 1, 2, 8, '2026-06-13T15:00:00.000Z', 'Wankhede Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (14, 1, 3, 4, '2026-06-14T15:00:00.000Z', 'M. Chinnaswamy Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (15, 1, 3, 5, '2026-06-15T15:00:00.000Z', 'Eden Gardens', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (16, 1, 3, 6, '2026-06-16T15:00:00.000Z', 'Hyderabad International Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (17, 1, 3, 7, '2026-06-17T15:00:00.000Z', 'M. Chinnaswamy Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (18, 1, 3, 8, '2026-06-18T15:00:00.000Z', 'Wankhede Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (19, 1, 4, 5, '2026-06-19T15:00:00.000Z', 'Wankhede Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (20, 1, 4, 6, '2026-06-20T15:00:00.000Z', 'Hyderabad International Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (21, 1, 4, 7, '2026-06-21T15:00:00.000Z', 'Arun Jaitley Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (22, 1, 4, 8, '2026-06-22T15:00:00.000Z', 'Eden Gardens', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (23, 1, 5, 6, '2026-06-23T15:00:00.000Z', 'Hyderabad International Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (24, 1, 5, 7, '2026-06-24T15:00:00.000Z', 'Arun Jaitley Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (25, 1, 5, 8, '2026-06-25T15:00:00.000Z', 'Hyderabad International Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (26, 1, 6, 7, '2026-06-26T15:00:00.000Z', 'Eden Gardens', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (27, 1, 6, 8, '2026-06-27T15:00:00.000Z', 'Arun Jaitley Stadium', 'upcoming', NULL);
INSERT INTO matches (id, tournament_id, team1_id, team2_id, scheduled_date, venue, status, winner_id) VALUES (28, 1, 7, 8, '2026-06-28T15:00:00.000Z', 'M. Chinnaswamy Stadium', 'upcoming', NULL);

